
export const AUTH_START = 'AUTH_START';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const LOGOUT = 'LOGOUT';

export const LOADING_TASKS_START = 'LOADING_TASKS_START';
export const LOADING_TASKS_COMPLETE = 'LOADING_TASKS_COMPLETE';
export const LOADING_TASK_FAILED = 'LOADING_TASK_FAILED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADDED_TASK = 'ADDED_TASK';

export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_CONTENT = 'EDIT_TASK_CONTENT';
export const EDIT_TASK_SAVE = 'EDIT_TASK_SAVE';